ibexa_logs_ui_index:
    path: /ibexa-logs-ui/{level}/{page}
    defaults: { _controller: IbexaLogsUi\Bundle\Controller\LogsManagerController::index, level: all, page: 1 }
    requirements:
        level: '\w+'
        page: '\d+'

ibexa_logs_ui_reload:
    path: /ibexa-logs-ui/reload
    defaults: { _controller: IbexaLogsUi\Bundle\Controller\LogsManagerController::reload }
