ibexa_logs_ui_index:
    path: /ibexa-logs-ui/{chunkId}
    defaults: { _controller: IbexaLogsUi\Bundle\Controller\LogsManagerController::index, chunkId: 1 }
    requirements:
        chunkId: '\d+'

ibexa_logs_ui_reload:
    path: /ibexa-logs-ui/reload
    defaults: { _controller: IbexaLogsUi\Bundle\Controller\LogsManagerController::reload }
