services:
    _defaults:
        public: false

    IbexaLogsUi\Bundle\Controller\LogsManagerController:
        tags:
            - { name: controller.service_arguments }
        arguments:
            $kernelCacheDir: '%kernel.cache_dir%'
            $monologLogger: '@monolog.logger'
        calls:
            - [ 'setContainer', [ '@service_container' ] ]
            - [ 'performAccessCheck', [ ] ]

    IbexaLogsUi\Bundle\EventSubscriber\MenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }
